/*
 * RaspiAPI
 * This is the server to function as interface for the rasperry pi in the alarm-clock project. It will provide options to interact with the local programs as well as Curl system data
 *
 * OpenAPI spec version: 1.0.0
 * Contact: lorenz.keefer@web.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SystemInfoApi
 */
@Ignore
public class SystemInfoApiTest {

    private final SystemInfoApi api = new SystemInfoApi();

    /**
     * Check the temperature of your pi
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void checkTempTest() throws ApiException {
        Long response = api.checkTemp();

        // TODO: test validations
    }
}
