/*
 * RaspiAPI
 * This is the server to function as interface for the rasperry pi in the alarm-clock project. It will provide options to interact with the local programs as well as Curl system data
 *
 * OpenAPI spec version: 1.0.0
 * Contact: lorenz.keefer@web.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
